cd ..
python train.py --train mnist --repulsive fashionmnist --reference_net log/reference/models/repulsive_train:mnist_repulsive:None_lambda:0.0_bandwidth:0.0_0_10epochs.pt --lambda_repulsive 0.05 --bandwidth_repulsive 10 --seed 0 --disable-cuda --id 0  --save_folder log/train:mnist_repulsive:fashionmnist_l:0.05_b:10 &
python train.py --train mnist --repulsive fashionmnist --reference_net log/reference/models/repulsive_train:mnist_repulsive:None_lambda:0.0_bandwidth:0.0_0_10epochs.pt --lambda_repulsive 0.05 --bandwidth_repulsive 10 --seed 1 --disable-cuda --id 1 --save_folder log/train:mnist_repulsive:fashionmnist_l:0.05_b:10  &
python train.py --train mnist --repulsive fashionmnist --reference_net log/reference/models/repulsive_train:mnist_repulsive:None_lambda:0.0_bandwidth:0.0_0_10epochs.pt --lambda_repulsive 0.05 --bandwidth_repulsive 10 --seed 2 --disable-cuda --id 2 --save_folder log/train:mnist_repulsive:fashionmnist_l:0.05_b:10  &
python train.py --train mnist --repulsive fashionmnist --reference_net log/reference/models/repulsive_train:mnist_repulsive:None_lambda:0.0_bandwidth:0.0_0_10epochs.pt --lambda_repulsive 0.05 --bandwidth_repulsive 10 --seed 3 --disable-cuda --id 3 --save_folder log/train:mnist_repulsive:fashionmnist_l:0.05_b:10  &
python train.py --train mnist --repulsive fashionmnist --reference_net log/reference/models/repulsive_train:mnist_repulsive:None_lambda:0.0_bandwidth:0.0_0_10epochs.pt --lambda_repulsive 0.05 --bandwidth_repulsive 10 --seed 4 --disable-cuda --id 4 --save_folder log/train:mnist_repulsive:fashionmnist_l:0.05_b:10  &
python train.py --train mnist --repulsive fashionmnist --reference_net log/reference/models/repulsive_train:mnist_repulsive:None_lambda:0.0_bandwidth:0.0_0_10epochs.pt --lambda_repulsive 0.05 --bandwidth_repulsive 10 --seed 5 --disable-cuda --id 5 --save_folder log/train:mnist_repulsive:fashionmnist_l:0.05_b:10  &
python train.py --train mnist --repulsive fashionmnist --reference_net log/reference/models/repulsive_train:mnist_repulsive:None_lambda:0.0_bandwidth:0.0_0_10epochs.pt --lambda_repulsive 0.05 --bandwidth_repulsive 10 --seed 6 --disable-cuda --id 6 --save_folder log/train:mnist_repulsive:fashionmnist_l:0.05_b:10  &
python train.py --train mnist --repulsive fashionmnist --reference_net log/reference/models/repulsive_train:mnist_repulsive:None_lambda:0.0_bandwidth:0.0_0_10epochs.pt --lambda_repulsive 0.05 --bandwidth_repulsive 10 --seed 7 --disable-cuda --id 7 --save_folder log/train:mnist_repulsive:fashionmnist_l:0.05_b:10  &
python train.py --train mnist --repulsive fashionmnist --reference_net log/reference/models/repulsive_train:mnist_repulsive:None_lambda:0.0_bandwidth:0.0_0_10epochs.pt --lambda_repulsive 0.05 --bandwidth_repulsive 10 --seed 8 --disable-cuda --id 8 --save_folder log/train:mnist_repulsive:fashionmnist_l:0.05_b:10  &
python train.py --train mnist --repulsive fashionmnist --reference_net log/reference/models/repulsive_train:mnist_repulsive:None_lambda:0.0_bandwidth:0.0_0_10epochs.pt --lambda_repulsive 0.05 --bandwidth_repulsive 10 --seed 9 --disable-cuda --id 9 --save_folder log/train:mnist_repulsive:fashionmnist_l:0.05_b:10  &
wait
