cd ..
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.01 --gpu 0 --seed 0 --id 0 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.01 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.01 --gpu 0 --seed 1 --id 1 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.01 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.01 --gpu 1 --seed 2 --id 2 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.01 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.01 --gpu 1 --seed 3 --id 3 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.01 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.01 --gpu 2 --seed 4 --id 4 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.01 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.01 --gpu 2 --seed 5 --id 5 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.01 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.01 --gpu 3 --seed 6 --id 6 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.01 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.01 --gpu 3 --seed 7 --id 7 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.01 &
wait
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.01 --gpu 0 --seed 8 --id 8 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.01 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.01 --gpu 0 --seed 9 --id 9 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.01 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.1 --gpu 1 --seed 0 --id 0 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.1 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.1 --gpu 1 --seed 1 --id 1 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.1 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.1 --gpu 2 --seed 2 --id 2 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.1 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.1 --gpu 2 --seed 3 --id 3 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.1 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.1 --gpu 3 --seed 4 --id 4 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.1 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.1 --gpu 3 --seed 5 --id 5 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.1 &
wait
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.1 --gpu 0 --seed 6 --id 6 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.1 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.1 --gpu 0 --seed 7 --id 7 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.1 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.1 --gpu 1 --seed 8 --id 8 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.1 &
python train_policy_color.py --train datasets/red_sphere --repulsive datasets/green_sphere --reference_net log/reference/models/reference_net_red_sphere.model --lambda_repulsive 10 --bandwidth_repulsive 0.1 --gpu 1 --seed 9 --id 9 --save_folder log/denn/train:red_sphere_repulsive:green_sphere_l:10_b:0.1 &
wait
